config/routes.rb
Cms::Application.routes.draw do
  resources :operations

  resources :menus

  resources :roles

  get "index/index"

  resources :users

  get 'get_full_url_by_commodity_no' => 'users#get_full_url_by_commodity_no'

  get 'ruby_server' => 'users#get_full_url_by_commodity_no'
  root to: 'index#index'

end

app/models/menu.rb
#encoding:utf-8
class Menu < ActiveRecord::Base
  self.primary_key = "sid"
  attr_accessible :click_url, :display, :name, :parent_path, :sid
  validates :sid,presence:{message:"主键不能为空！"}
  has_many :role_menus
  has_many :roles,through: :role_menus

  has_many :operations


end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menus }
    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @menu = Menu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/new
  # GET /menus/new.json
  def new
    @menu = Menu.new
    @menu.id = get_sid
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/1/edit
  def edit
    @menu = Menu.find(params[:id])
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menus/1
  # PUT /menus/1.json
  def update
    @menu = Menu.find(params[:id])

    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sid %><br />
    <%= f.text_field :sid %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parent_path %><br />
    <%= f.text_field :parent_path %>
  </div>
  <div class="field">
    <%= f.label :click_url %><br />
    <%= f.text_field :click_url %>
  </div>
  <div class="field">
    <%= f.label :display %><br />
    <%= f.check_box :display %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<h1>Listing menus</h1>

<table>
  <tr>
    <th>Sid</th>
    <th>Name</th>
    <th>Parent path</th>
    <th>Click url</th>
    <th>Display</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menus.each do |menu| %>
  <tr>
    <td><%= menu.sid %></td>
    <td><%= menu.name %></td>
    <td><%= menu.parent_path %></td>
    <td><%= menu.click_url %></td>
    <td><%= menu.display %></td>
    <td><%= link_to 'Show', menu %></td>
    <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
    <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sid:</b>
  <%= @menu.sid %>
</p>

<p>
  <b>Name:</b>
  <%= @menu.name %>
</p>

<p>
  <b>Parent path:</b>
  <%= @menu.parent_path %>
</p>

<p>
  <b>Click url:</b>
  <%= @menu.click_url %>
</p>

<p>
  <b>Display:</b>
  <%= @menu.display %>
</p>


<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>