config/routes.rb
Cms::Application.routes.draw do
  resources :operations

  resources :menus

  resources :roles

  get "index/index"

  resources :users

  get 'get_full_url_by_commodity_no' => 'users#get_full_url_by_commodity_no'

  get 'ruby_server' => 'users#get_full_url_by_commodity_no'
  root to: 'index#index'

end

app/models/operation.rb
#encoding:utf-8
class Operation < ActiveRecord::Base
  self.primary_key = "sid"
  attr_accessible :action_name, :sid, :url
  validates :sid,presence:{message:"主键不能为空！"}
  validates :action_name,length: {minimum: 2,maximum: 32,message:"操作名称应大于2个字符，小于30个字符"}
  validates :url,presence: {message:"url不能为空"}
  belongs_to :menu
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  # GET /operations
  # GET /operations.json
  def index
    @operations = Operation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @operations }
    end
  end

  # GET /operations/1
  # GET /operations/1.json
  def show
    @operation = Operation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @operation }
    end
  end

  # GET /operations/new
  # GET /operations/new.json
  def new
    @operation = Operation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @operation }
    end
  end

  # GET /operations/1/edit
  def edit
    @operation = Operation.find(params[:id])
  end

  # POST /operations
  # POST /operations.json
  def create
    @operation = Operation.new(params[:operation])

    respond_to do |format|
      if @operation.save
        format.html { redirect_to @operation, notice: 'Operation was successfully created.' }
        format.json { render json: @operation, status: :created, location: @operation }
      else
        format.html { render action: "new" }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /operations/1
  # PUT /operations/1.json
  def update
    @operation = Operation.find(params[:id])

    respond_to do |format|
      if @operation.update_attributes(params[:operation])
        format.html { redirect_to @operation, notice: 'Operation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation = Operation.find(params[:id])
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to operations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= form_for(@operation) do |f| %>
  <% if @operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
      <% @operation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sid %><br />
    <%= f.text_field :sid %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :action_name %><br />
    <%= f.text_field :action_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render 'form' %>

<%= link_to 'Show', @operation %> |
<%= link_to 'Back', operations_path %>

app/views/operations/index.html.erb
<h1>Listing operations</h1>

<table>
  <tr>
    <th>Sid</th>
    <th>Url</th>
    <th>Action name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @operations.each do |operation| %>
  <tr>
    <td><%= operation.sid %></td>
    <td><%= operation.url %></td>
    <td><%= operation.action_name %></td>
    <td><%= link_to 'Show', operation %></td>
    <td><%= link_to 'Edit', edit_operation_path(operation) %></td>
    <td><%= link_to 'Destroy', operation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Operation', new_operation_path %>

app/views/operations/new.html.erb
<h1>New operation</h1>

<%= render 'form' %>

<%= link_to 'Back', operations_path %>

app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sid:</b>
  <%= @operation.sid %>
</p>

<p>
  <b>Url:</b>
  <%= @operation.url %>
</p>

<p>
  <b>Action name:</b>
  <%= @operation.action_name %>
</p>


<%= link_to 'Edit', edit_operation_path(@operation) %> |
<%= link_to 'Back', operations_path %>